cabal-version: 3.0
name:          TypeClasses
version:       0.1.0.0
maintainer:    daniel.kroeni@fhnw.ch
author:        Daniel Kröni
build-type:    Simple

test-suite map
    type:             exitcode-stdio-1.0
    main-is:          Map/Tests.hs
    other-modules:    Map.TreeMap
    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.17 && <5,
        hspec ==2.11.17,
        hspec-contrib,
        QuickCheck,
        HUnit

test-suite imp
    type:             exitcode-stdio-1.0
    main-is:          Lang/Tests.hs
    other-modules:
        Map.TreeMap
        Lang.Imp

    default-language: Haskell2010
    ghc-options:      -Wall
    build-depends:
        base >=4.17 && <5,
        hspec ==2.11.17,
        hspec-contrib,
        QuickCheck,
        HUnit
